MAX_NUMBER_OF_PROCESSES = 2
TIMELIMIT = 900
LP_ITERATIONS = 4
MIP_ITERATION_SCALING = 1.5
RESULT_PATH = 'results/'
TOPOLOGY_FILE_LOCATION = 'data/CapacitatedTopologyZoo/Generalized/'
FLOW_FILE_LOCATION = 'data/TopologyZooFlows/Flow10x/'